<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_English</name>
   <tag></tag>
   <elementGuidId>27764d72-6da4-42ac-a972-22e78473149e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-listbox-option-v-0-0-0-17']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-listbox-option-v-0-0-0-17</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ba555c9f-78c3-4529-85c2-2525020ec649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-none relative items-center gap-1 cursor-pointer hover:text-brand-500 font-medium flex justify-center rounded-xs p-2 text-sm text-grey-800 dark:bg-gray-900 bg-grey-50 text-brand-500</value>
      <webElementGuid>f4342d71-e91a-4eeb-9687-98927f056faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-listbox-option-v-0-0-0-17</value>
      <webElementGuid>f581cc74-a8d9-4e11-a957-c4f27d392725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>45c58efb-97d4-4341-b679-6aca94d17431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d35d19bc-b168-4eaa-8777-ad7696cbd107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d80cd779-d2be-4761-94fe-9e3f4cdeaf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>5070d466-35f4-41ec-a087-4999a638f89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>895677fd-e690-42b0-9bb0-42bcd5e36d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-option-v-0-0-0-17&quot;)</value>
      <webElementGuid>46a36ba4-09eb-4983-836e-d4da5e1532da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-v-0-0-0-17']</value>
      <webElementGuid>c021b719-73e6-4a83-ae0c-351506162435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-listbox-options-v-0-0-0-15']/li[2]</value>
      <webElementGuid>a326bffe-26b3-4696-b795-1cda2ede7cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::li[1]</value>
      <webElementGuid>b020e6f3-ef59-4010-bee8-fc8c58ba9b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta MHEWS'])[1]/following::li[2]</value>
      <webElementGuid>a81c76c8-e5e0-4653-adb9-d3cfc3cb46ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Hazard Early Warning System'])[2]/preceding::li[1]</value>
      <webElementGuid>a66d6250-f4c0-499d-8a07-30690e325ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>52533e9d-9d52-4966-b9fd-71ac2b8b4332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-listbox-option-v-0-0-0-17' and (text() = 'English' or . = 'English')]</value>
      <webElementGuid>bb19b767-9e79-4de1-987b-f90a710da6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
