<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back to Sign In</name>
   <tag></tag>
   <elementGuidId>d0d00d78-23c8-4ae8-abb4-6f58ca7392d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Back to Sign In$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f91430c0-9f6b-4acb-bc7b-ffd501d1fc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ecb5db40-0d0d-48c5-b2e1-9ba9123bb8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 font-medium rounded-xs text-base gap-x-2.5 px-3.5 py-2.5 dark:text-brand-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-brand-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-brand-400 bg-transparent ring-1 ring-brand-500 ring-inset text-brand-400 hover:ring-brand-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-brand-100 focus-visible:ring-1 focus-visible:ring-brand-200 w-full flex justify-center items-center flex-1</value>
      <webElementGuid>48326dc7-bc9e-4bd0-90de-eb46d5c0a9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to Sign In</value>
      <webElementGuid>29db2c7e-f342-4b09-acac-1b18bb0c9646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;flex sm:p-6 h-screen&quot;]/div[@class=&quot;flex justify-end w-full rounded-lg bg-grey-100 sm:bg-cover sm:bg-center&quot;]/div[@class=&quot;w-full sm:w-1/2 sm:p-14&quot;]/div[@class=&quot;flex flex-col bg-grey-100 rounded-xs h-full p-4 sm:px-16 sm:py-8 overflow-y-auto justify-center&quot;]/div[@class=&quot;flex flex-col space-y-3 mb-7 sm:px-10&quot;]/button[@class=&quot;focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 font-medium rounded-xs text-base gap-x-2.5 px-3.5 py-2.5 dark:text-brand-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-brand-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-brand-400 bg-transparent ring-1 ring-brand-500 ring-inset text-brand-400 hover:ring-brand-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-brand-100 focus-visible:ring-1 focus-visible:ring-brand-200 w-full flex justify-center items-center flex-1&quot;]</value>
      <webElementGuid>6009170f-ae29-4582-8098-3c1ced8631a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>7da45680-a506-4405-97cc-99b4e2f00127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div/div[2]/button</value>
      <webElementGuid>54c96135-b41c-4f4e-afeb-4aa45da5060f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Account'])[1]/following::button[1]</value>
      <webElementGuid>29df85a5-fb7b-4cf9-998a-caee2b3cd085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Sign In'])[1]/following::button[2]</value>
      <webElementGuid>0788ddb7-f47d-4ba3-a21a-3cd34f257339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>68569523-17a9-41dd-8624-38ef3d7bb2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Back to Sign In' or . = 'Back to Sign In')]</value>
      <webElementGuid>5deace7a-a4f7-4b2e-bae3-ee2fada1709f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
