<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back_1</name>
   <tag></tag>
   <elementGuidId>878461fb-1b0a-4d4c-a048-020fe9812a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Back&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f59d214-ed1d-419f-ba9d-2ca5df064c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f15d0574-be0f-40c7-931f-cb4d63d8212d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 w-40 h-[34px] justify-center font-medium rounded-sm text-xs gap-x-1.5 px-2.5 py-1.5 dark:text-primary-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-primary-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-primary-400 bg-transparent ring-1 ring-inset hover:ring-primary-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-primary-100 focus-visible:ring-1 focus-visible:ring-brand-200 text-brand-500 ring-brand-500 inline-flex items-center</value>
      <webElementGuid>40ab700e-e024-4e38-bb17-803a9aded1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back</value>
      <webElementGuid>c4cff2c1-9336-4716-ad27-1420f694d315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-v-0-4-1-14&quot;)/div[@class=&quot;flex rounded-lg overflow-hidden h-full&quot;]/div[@class=&quot;w-80 p-10 text-center flex flex-col justify-center items-center&quot;]/div[@class=&quot;border-t border-grey-200 mt-4 pt-4 flex flex-col gap-2 items-center&quot;]/button[@class=&quot;focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 w-40 h-[34px] justify-center font-medium rounded-sm text-xs gap-x-1.5 px-2.5 py-1.5 dark:text-primary-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-primary-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-primary-400 bg-transparent ring-1 ring-inset hover:ring-primary-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-primary-100 focus-visible:ring-1 focus-visible:ring-brand-200 text-brand-500 ring-brand-500 inline-flex items-center&quot;]</value>
      <webElementGuid>27e91717-db4c-4431-80e5-0ac227d2d69d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>51d94ffc-39bc-4504-baff-90a9d29ae496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-v-0-4-1-14']/div/div[2]/div/button[2]</value>
      <webElementGuid>faf16f75-6b7a-48e8-b5d9-6e625dfb600a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard MHEWS'])[1]/following::button[1]</value>
      <webElementGuid>2ce931eb-7fec-4aa0-b7c5-0003ad426d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Detail'])[1]/following::button[22]</value>
      <webElementGuid>e109881b-0d0a-45c7-af42-1dfa08da6ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]</value>
      <webElementGuid>690b3e33-dab3-498b-8267-a5a99a0f9c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Back' or . = 'Back')]</value>
      <webElementGuid>54d95fe2-868d-47f4-89a2-858a5bbf73c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
