<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete Layer_1</name>
   <tag></tag>
   <elementGuidId>5bfc70cf-c8ee-48c1-957c-768ace71ba55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-menu-item-v-0-2-1-155']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-2-1-155</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Delete Layer&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99d69acc-5000-4d83-a5ad-aac407185c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-grey-300 dark:bg-grey-700 group flex w-full items-center gap-3 rounded-xxs p-2 text-xs text-brand-500</value>
      <webElementGuid>6e0ca5db-a4ce-47e8-86af-a80f28561e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-v-0-2-1-155</value>
      <webElementGuid>3f8d8a40-8d4a-4ec3-a17f-b50fc1374507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>12b357e3-496b-492e-99ff-75a16dbb9ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bb66978b-5ed8-4dec-8c73-0d1935b11237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>5d0e44d4-b9d6-42d2-bb46-8f1c337ab2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Delete Layer </value>
      <webElementGuid>cd5c92b1-4d64-4aef-9773-2fb00e5718a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-2-1-155&quot;)</value>
      <webElementGuid>320ae8c4-8bcb-4bab-8228-d4a5b7ce526f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-menu-item-v-0-2-1-155']</value>
      <webElementGuid>949facb8-095d-4abc-bfe4-1cf2e7b220c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-v-0-2-1-144']/button[4]</value>
      <webElementGuid>907215c4-8c3f-4a2b-a597-7030bad367fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Data Table'])[1]/following::button[1]</value>
      <webElementGuid>a2c46048-bae8-4240-8a0b-8d4ba105e876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Layer Info'])[1]/following::button[2]</value>
      <webElementGuid>01fca298-c296-4265-bd04-3e3f4477492f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete Layer']/parent::*</value>
      <webElementGuid>0c2692fe-9ee2-4086-ba14-514da3d90a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[4]</value>
      <webElementGuid>504cd80c-bc9b-49db-a1b8-439496c740c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-menu-item-v-0-2-1-155' and (text() = ' Delete Layer ' or . = ' Delete Layer ')]</value>
      <webElementGuid>eb784110-544a-41b8-b1bb-481f2a1154ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
