<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Zoom To Fit_1</name>
   <tag></tag>
   <elementGuidId>91f4a82c-0f5c-4848-9146-2bbaf4839e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-menu-item-v-0-2-1-84']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-2-1-84</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Zoom To Fit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ead2fb4-75f6-4c2b-bf08-dbdaef1a634b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-grey-300 dark:bg-grey-700 group flex w-full items-center gap-3 rounded-xxs p-2 text-xs text-black dark:text-white</value>
      <webElementGuid>7822c25b-294f-4adb-860d-f690e1178e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-v-0-2-1-84</value>
      <webElementGuid>1e5519fd-3e14-40e0-8ebd-1672a8aebe71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>48bd2f97-02c0-4fc8-a250-bd03c42ba0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>67513916-6e59-4818-844f-9d7da7bd3041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>9e148937-ca3c-4531-b8e7-9606e267b74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Zoom To Fit </value>
      <webElementGuid>3872cc10-a734-43e1-b713-bf3c7017f32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-2-1-84&quot;)</value>
      <webElementGuid>cc94cd92-63ae-4e13-97cc-663004b613f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-menu-item-v-0-2-1-84']</value>
      <webElementGuid>9b83f30b-894b-47b3-a590-817c12277d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-v-0-2-1-53']/button</value>
      <webElementGuid>75f9b3f3-9163-4a0d-afe2-1f8d937d9ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Catalogue'])[1]/following::button[19]</value>
      <webElementGuid>db41834d-1546-4d88-b731-ced9563fa3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export JSON'])[1]/preceding::button[1]</value>
      <webElementGuid>f1390641-6b90-422c-9640-1690225cfc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export GPKG'])[1]/preceding::button[2]</value>
      <webElementGuid>158957f1-2705-4df5-855d-ded961d1f7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Zoom To Fit']/parent::*</value>
      <webElementGuid>1da5afed-656b-47fe-af19-ff7460458ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div[4]/button</value>
      <webElementGuid>14b18ebb-93b0-4786-ad20-2a7e77cc2823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-menu-item-v-0-2-1-84' and (text() = ' Zoom To Fit ' or . = ' Zoom To Fit ')]</value>
      <webElementGuid>d143d3d4-b8fd-4c87-a089-c13b25f83f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
