<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Share Map_h-10 max-w-56 object-contain _834264</name>
   <tag></tag>
   <elementGuidId>4a778a40-2bf4-40b1-85cd-7c807b9a2925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.h-10.max-w-56.object-contain.object-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div/div[2]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ea865ef0-12a6-4713-8762-25feea24287a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/panel/assets/1e14f9f7-dff9-4512-8e10-186289920cd6</value>
      <webElementGuid>f025a8ea-e118-4464-954d-fe02304323d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/panel/assets/1e14f9f7-dff9-4512-8e10-186289920cd6 1x, /panel/assets/1e14f9f7-dff9-4512-8e10-186289920cd6 2x</value>
      <webElementGuid>d1249abb-b1c4-4f74-b43c-8be5cf9abccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-10 max-w-56 object-contain object-center</value>
      <webElementGuid>2081a644-e109-400a-97a4-94ac71a13a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;z-50 flex flex-col print:hidden&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;w-0 p-0 relative bg-grey-100 rounded-xs flex items-center justify-between z-50 min-w-fit transition-all duration-300 ease-in-out&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;relative flex items-center p-3 gap-3 h-12&quot;]/img[@class=&quot;h-10 max-w-56 object-contain object-center&quot;]</value>
      <webElementGuid>3f3534ce-bcfd-4cae-b592-a2e1c7bbe2b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div[2]/div/div/div/img</value>
      <webElementGuid>b0d35abb-e0c3-4422-8f3b-47094a4c5772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d8a335e9-c5a7-44c9-9059-0c61bb36ed52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/panel/assets/1e14f9f7-dff9-4512-8e10-186289920cd6']</value>
      <webElementGuid>4f037d1e-f845-4e10-8432-3338115b88e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
