<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi Hazard Early Warning System_email</name>
   <tag></tag>
   <elementGuidId>15db6f7a-fc6e-4a45-b8af-768359ac1375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#v-0-1-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='v-0-1-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8c70a30-2c55-42c6-b375-bbf039c8b7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>v-0-1-1</value>
      <webElementGuid>a3fc83ae-0958-4ed3-ab98-f957220760bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e3f8c051-0f90-4a23-b69c-3c145c9576fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>837e4605-c451-49e3-b598-c2d349eaf2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>adae07dd-b7cb-44aa-b955-191727f93893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative block w-full disabled:cursor-not-allowed disabled:opacity-75 focus:outline-none border-0 form-input rounded-xs placeholder-gray-400 dark:placeholder-gray-500 text-base px-3.5 py-2.5 shadow-sm bg-grey-200 dark:bg-grey-700 text-grey-black dark:text-white ring-1 ring-inset ring-grey-600 dark:ring-grey-700 focus:ring-2 focus:ring-primary-500 dark:focus:ring-primary-400 placeholder:text-grey-500</value>
      <webElementGuid>884cca67-8fc0-4391-a12f-4765e9e4c697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v-0-1-1&quot;)</value>
      <webElementGuid>0cf73a70-2520-47fa-9551-be4be30686e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='v-0-1-1']</value>
      <webElementGuid>a57f388d-f679-4eda-b56f-81eb2c9c067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>34c9e6b0-a0eb-49c6-82d7-41b6660d089e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d46c89ea-2fd1-42de-92ee-3df68b539581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'v-0-1-1' and @name = 'email' and @type = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>6bb3ee8f-f5d2-4aca-a88a-fb6227d1afba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
