<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Flood Hazard Information</name>
   <tag></tag>
   <elementGuidId>c396d466-ef4b-4c78-b3d5-c516fc2f4769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-listbox-option-v-0-5-0-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-listbox-option-v-0-5-0-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Flood Hazard Information&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e320d5ef-130b-4104-b968-0831a842f89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-none relative flex items-center justify-between gap-1 cursor-pointer hover:text-brand-500 font-medium rounded-xs p-2 text-sm text-grey-800 dark:bg-gray-900 bg-grey-50 text-brand-500</value>
      <webElementGuid>87a7f117-7e9c-40c0-b63c-bf30506be4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-listbox-option-v-0-5-0-19</value>
      <webElementGuid>71fab1bd-fb9b-44e4-930e-e4d000eb6466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8b6bf5db-fe27-437e-8bd7-da2ce73792c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>61307b55-38a9-4fc8-adfe-755c5b2506a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce2f37e5-1317-4695-860b-79865e9f33f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>71618691-e37f-4fe0-b3b3-8b24defce667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flood Hazard Information</value>
      <webElementGuid>91928e47-a4b4-4151-816d-01af1c716c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-option-v-0-5-0-19&quot;)</value>
      <webElementGuid>1e145a1a-7dba-4b9c-8d35-77f4633d970f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-v-0-5-0-19']</value>
      <webElementGuid>c74624e4-ae7e-4ec2-9852-88d3191ee28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-listbox-options-v-0-5-0-18']/li</value>
      <webElementGuid>4901db28-5b04-4dc7-81a0-fb0b497e8f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tsunami Hazard Information'])[1]/following::li[1]</value>
      <webElementGuid>2bb1a11e-ac45-4328-a787-0c98b5042d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tsunami Hazard Information'])[2]/preceding::li[1]</value>
      <webElementGuid>f8be4960-b91e-42a4-be53-fc802c93a315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>a9d71f08-868e-4124-bb2e-30eb7bdddf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-listbox-option-v-0-5-0-19' and (text() = 'Flood Hazard Information' or . = 'Flood Hazard Information')]</value>
      <webElementGuid>2ac9c6b9-1498-4cc8-bd44-0df0de2acc10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
