<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 Days AgoWarning Tsunami PD-4Warning T_df214e</name>
   <tag></tag>
   <elementGuidId>20012655-8d24-4bd9-a65a-6d1bb128cee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-popover-panel-v-0-0-0-9']/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df1a4416-b939-4157-870b-a4e62e7c06c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-white/45 cursor-pointer p-2 rounded-xs border bg-white/45 shadow-sm flex gap-2 items-center</value>
      <webElementGuid>8d194558-30c0-4d01-be12-65d8b227809d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b26355a0-93cd-4b20-a41d-60dcb8a650df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Days AgoWarning Tsunami PD-4Warning Tsunami PD-4</value>
      <webElementGuid>7001e0a3-3aa1-45e3-97bd-56fc9757ffa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-panel-v-0-0-0-9&quot;)/div[@class=&quot;relative bg-grey-100 px-2 pb rounded-xs shadow-lg space-y-2 max-h-[50dvh] overflow-y-auto&quot;]/div[@class=&quot;space-y-2&quot;]/div[@class=&quot;space-y-2 max-h-80 overflow-y-auto&quot;]/div[@class=&quot;border-white/45 cursor-pointer p-2 rounded-xs border bg-white/45 shadow-sm flex gap-2 items-center&quot;]</value>
      <webElementGuid>876fa5e9-c9a0-4785-b7cf-ed2d544f6aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-popover-panel-v-0-0-0-9']/div/div[3]/div/div</value>
      <webElementGuid>4ac6f922-550e-48bf-b32f-4a10659c7b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::div[7]</value>
      <webElementGuid>97763550-fd28-43cc-b2e8-986c38302a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MHEWS Map'])[1]/following::div[19]</value>
      <webElementGuid>64803a62-d054-4633-a468-e9eaf667bece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Hazard Early Warning System'])[2]/preceding::div[32]</value>
      <webElementGuid>e147acdb-5f5d-46e8-8acf-dd21a12b19ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitigation'])[1]/preceding::div[34]</value>
      <webElementGuid>b57d53fb-0e86-452e-985c-8ed976cfe8e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>385d0b62-f189-49b8-93ee-dc62849e8526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 Days AgoWarning Tsunami PD-4Warning Tsunami PD-4' or . = '1 Days AgoWarning Tsunami PD-4Warning Tsunami PD-4')]</value>
      <webElementGuid>ff718f52-a03d-403e-a5e2-7b2e7ce39cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
