<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MHEWS Map_cursor-pointer border border-_66deac</name>
   <tag></tag>
   <elementGuidId>bb0b9d7b-67e7-4ec6-880e-c72dba2edd95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-popover-button-v-0-0-0-7']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cursor-pointer.border.border-grey-500.rounded-sm.p-2.h-10.w-10.flex.items-center.justify-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6a76e1c-334a-4846-8d84-c96ad2a4a264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer border border-grey-500 rounded-sm p-2 h-10 w-10 flex items-center justify-center</value>
      <webElementGuid>4ce9eaa9-f84e-4fc8-90b7-e31360adfb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-popover-button-v-0-0-0-7&quot;)/div[@class=&quot;cursor-pointer border border-grey-500 rounded-sm p-2 h-10 w-10 flex items-center justify-center&quot;]</value>
      <webElementGuid>0fd2d677-95c2-4607-a7fc-56be28b8f972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='headlessui-popover-button-v-0-0-0-7']/div</value>
      <webElementGuid>04cd74f1-125b-4509-8825-cb49c89e6409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MHEWS Map'])[1]/following::div[9]</value>
      <webElementGuid>bd61f85c-3562-4748-818e-a994b0bc644a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Hazard Early Warning System'])[2]/preceding::div[2]</value>
      <webElementGuid>c7d3f2f3-361b-42b0-bebe-a4c97ae4e2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitigation'])[1]/preceding::div[4]</value>
      <webElementGuid>44cec662-cdd2-40ca-90b5-21bb19836115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/button/div</value>
      <webElementGuid>18260e99-41d0-42ae-b051-104470c982df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
