<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Indonesia_1</name>
   <tag></tag>
   <elementGuidId>e18f9cf3-a82b-4cfa-af8c-6aace4c4bf76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-listbox-option-v-0-0-0-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-listbox-option-v-0-0-0-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>49f4691b-7eb1-4056-87b1-5f86fefadb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-none relative items-center gap-1 cursor-pointer hover:text-brand-500 font-medium flex justify-center rounded-xs p-2 text-sm text-grey-800 dark:bg-gray-900 bg-grey-50 text-brand-500</value>
      <webElementGuid>aad96453-c2f6-4ca4-8c14-7d7e135d03ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-listbox-option-v-0-0-0-19</value>
      <webElementGuid>55589be1-37f6-4f36-9e9b-1efb6bfb26e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>9ac37ffe-aff0-4f8b-95df-ddecf1f8860b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ba7cf923-d0db-47b3-ac87-268401b88633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf7affe1-1263-4324-88c5-874294fe1e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>c8bfec73-65a3-4ea7-add4-fa37695b2d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia</value>
      <webElementGuid>2e92a3c3-2ea6-4b1a-996b-5df5afbcef9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-listbox-option-v-0-0-0-19&quot;)</value>
      <webElementGuid>82fef397-e1f5-48dc-ba10-7c34635005f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-listbox-option-v-0-0-0-19']</value>
      <webElementGuid>c4aa21c5-b01f-4ed8-ac2f-6385d551e6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-listbox-options-v-0-0-0-18']/li</value>
      <webElementGuid>d5b2b74d-65e9-4754-ba8d-5cd9118c982f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MHEWS Map'])[1]/following::li[1]</value>
      <webElementGuid>513a44c3-0e59-4d66-aba6-8dc68a17f664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::li[1]</value>
      <webElementGuid>ccb6a8bc-bdf7-4f8f-a90a-5840bb56b834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>e6631e3d-5cab-438a-b8e1-93e6a7249920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-listbox-option-v-0-0-0-19' and (text() = 'Indonesia' or . = 'Indonesia')]</value>
      <webElementGuid>1859cf65-2788-488a-ba99-461d8518b402</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
