<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Informasi Multi Bencana</name>
   <tag></tag>
   <elementGuidId>caa10e26-8782-4d78-9ec2-95704da69ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-menu-item-v-0-2-0-20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-2-0-20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8e9d2d0-f0a5-48e1-9490-fe2dbda1398d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex items-center gap-1.5 w-full px-1.5 py-1.5 text-xs rounded-xs bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white</value>
      <webElementGuid>401ae9b0-d0b8-49d3-87bc-9eac06bb33e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-v-0-2-0-20</value>
      <webElementGuid>156c52da-c48c-4e65-8bb4-c9a17c1f1128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>bb90a53f-2184-4a8d-b1e7-9c84d057be54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>236c9bd1-db57-4166-b7ee-62ff70ae1edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>3a33b2e2-e968-4ec2-9072-ab07510515d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Multi Bencana</value>
      <webElementGuid>3c92bd6d-a438-417e-a10e-86753d520a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-2-0-20&quot;)</value>
      <webElementGuid>7c0ea07a-6aba-4ca7-9b00-e603ec2ad9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-menu-item-v-0-2-0-20']</value>
      <webElementGuid>d8d1c1c2-c131-4b3b-a8ca-0e0e4bcb739d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-v-0-2-0-17']/div/button[3]</value>
      <webElementGuid>8a143860-23fd-456a-8f6a-29d9e45b2ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Bahaya Tsunami'])[1]/following::button[1]</value>
      <webElementGuid>108edee6-c56a-4c17-b517-e7bd62e42e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Bahaya Banjir'])[1]/following::button[2]</value>
      <webElementGuid>54a52d8f-2243-48a8-af5c-4c8ba2f19717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Hazard Early Warning System'])[2]/preceding::button[3]</value>
      <webElementGuid>97c044f9-6f8f-467a-87e2-b394322eaa21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>b485d676-6edd-4d1c-9556-9635945fcb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-menu-item-v-0-2-0-20' and (text() = 'Informasi Multi Bencana' or . = 'Informasi Multi Bencana')]</value>
      <webElementGuid>be0059c0-0a97-43e3-a191-0fb66a6a5bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
