<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Latest Alerts</name>
   <tag></tag>
   <elementGuidId>1c3eee26-dbff-4092-b6c8-049e281ace63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>184cb136-cbd4-4125-8b76-3e7bc8b536df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9faa3186-ac83-45c6-8bb2-04cb97da177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 h-14 justify-center flex-grow font-medium rounded-sm text-sm gap-x-1.5 px-2.5 py-1.5 shadow-sm dark:text-gray-900 hover:bg-primary-600 disabled:bg-primary-500 aria-disabled:bg-primary-500 dark:bg-primary-400 dark:hover:bg-primary-500 dark:disabled:bg-primary-400 dark:aria-disabled:bg-primary-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500 dark:focus-visible:outline-primary-400 bg-brand-600 text-white inline-flex items-center</value>
      <webElementGuid>c42fb085-c4a7-4958-bf5d-e01a21e34829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latest Alerts</value>
      <webElementGuid>4d6e77cf-08a9-4f11-90c4-1935235bf32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;mt-9 relative&quot;]/div[@class=&quot;relative w-full h-full sm:h-[50rem] p-3&quot;]/div[@class=&quot;w-full h-full bg-cover bg-center rounded-lg p-3 flex flex-col&quot;]/div[@class=&quot;grid grid-cols-1 sm:grid-cols-3 gap-2&quot;]/div[@class=&quot;relative overflow-hidden bg-grey-100 rounded-lg pt-6 px-3 pb-3 flex flex-col justify-between gap-1&quot;]/div[@class=&quot;flex gap-2 pt-1&quot;]/button[@class=&quot;focus:outline-none disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 h-14 justify-center flex-grow font-medium rounded-sm text-sm gap-x-1.5 px-2.5 py-1.5 shadow-sm dark:text-gray-900 hover:bg-primary-600 disabled:bg-primary-500 aria-disabled:bg-primary-500 dark:bg-primary-400 dark:hover:bg-primary-500 dark:disabled:bg-primary-400 dark:aria-disabled:bg-primary-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary-500 dark:focus-visible:outline-primary-400 bg-brand-600 text-white inline-flex items-center&quot;]</value>
      <webElementGuid>527ae376-9f49-4c73-b2f9-04b7a9853984</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>74295729-574d-41ae-a0ba-99c6b94c1ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div[2]/div/div/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>342b2433-76d9-43b0-9a99-eb310e100e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitigation'])[1]/following::button[1]</value>
      <webElementGuid>4482129f-d88d-4a52-9b00-c76e102726fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi Hazard Early Warning System'])[2]/following::button[2]</value>
      <webElementGuid>2e2b8b10-d42b-43e1-8ac1-2cb0418fbedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mitigation'])[2]/preceding::button[1]</value>
      <webElementGuid>a47ebe77-24ee-4ffb-a9b8-b0034223cb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>0d4f7653-9168-4835-a396-315945af44aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Latest Alerts' or . = 'Latest Alerts')]</value>
      <webElementGuid>e9cb856a-47c6-4b51-b229-4bb0bc07d689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
