<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Informasi Bahaya Tsunami</name>
   <tag></tag>
   <elementGuidId>9fdb7656-0684-498a-b70e-1a3fd1abd5e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='headlessui-menu-item-v-0-4-0-19']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-menu-item-v-0-4-0-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24907ed1-1fb8-429e-a01d-552b76f86751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group flex items-center gap-1.5 w-full px-1.5 py-1.5 text-xs rounded-xs bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white</value>
      <webElementGuid>f213832e-2a52-4e03-b1a8-f1039bdda0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-menu-item-v-0-4-0-19</value>
      <webElementGuid>ccadd7fc-a0f9-442f-a294-6dd045a63ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>58e3da3c-c474-4de7-9c21-7203e1d1a9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ce8c6d7d-e954-487f-adc6-6306a9b422bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>b9298069-a2e1-4ed5-9600-b051d2abafaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informasi Bahaya Tsunami</value>
      <webElementGuid>6d3e34e3-3c0d-4f39-b6e5-f8ce82a28fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-menu-item-v-0-4-0-19&quot;)</value>
      <webElementGuid>eff5babc-029b-4b98-b6df-1d67dff7049b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='headlessui-menu-item-v-0-4-0-19']</value>
      <webElementGuid>37277951-b502-43bc-8817-f74f046fa6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-menu-items-v-0-4-0-17']/div/button[2]</value>
      <webElementGuid>b2452908-039f-4cd7-962b-0bbdca6bc632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Bahaya Banjir'])[1]/following::button[1]</value>
      <webElementGuid>b81fc4da-14f7-46dd-88ba-abcfb5a93de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peta MHEWS'])[1]/following::button[2]</value>
      <webElementGuid>3580ad7a-54ae-4ff4-8f55-d07dca77f0e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Multi Bencana'])[1]/preceding::button[1]</value>
      <webElementGuid>0b7bd3a9-5c85-4e65-b2d2-5d96b74586ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[2]/div/div/div/button[2]</value>
      <webElementGuid>dce77301-44a9-4207-9092-fcf68af3945e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'headlessui-menu-item-v-0-4-0-19' and (text() = 'Informasi Bahaya Tsunami' or . = 'Informasi Bahaya Tsunami')]</value>
      <webElementGuid>f555300f-0708-4da5-9756-fca5ecbe145c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
