<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batalkan</name>
   <tag></tag>
   <elementGuidId>720597e4-9d21-4d29-a8ff-03daa3afb610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[26]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>831e1c76-09dc-419e-8bef-7902f467f778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7256567-9903-41d3-a9e0-328c23aec5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 w-full h-9 justify-center font-medium rounded-sm text-sm gap-x-1.5 px-2.5 py-1.5 dark:text-brand-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-brand-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-brand-400 bg-transparent ring-1 ring-brand-500 ring-inset text-brand-400 hover:ring-brand-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-brand-100 focus-visible:ring-1 focus-visible:ring-brand-200 flex items-center</value>
      <webElementGuid>3a873f32-9169-471c-894e-646bb1b611e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batalkan</value>
      <webElementGuid>18269be9-2919-49f0-bcb4-9c895090a338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-v-0-2-18&quot;)/div[@class=&quot;rounded-xs shadow bg-white dark:bg-gray-900&quot;]/div[@class=&quot;px-3 py-1 sm:px-4 sm:py-3&quot;]/div[@class=&quot;rounded-sm grid grid-cols-2 gap-2&quot;]/button[@class=&quot;focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 aria-disabled:cursor-not-allowed aria-disabled:opacity-75 flex-shrink-0 w-full h-9 justify-center font-medium rounded-sm text-sm gap-x-1.5 px-2.5 py-1.5 dark:text-brand-400 disabled:bg-transparent aria-disabled:bg-transparent dark:hover:bg-brand-950 dark:disabled:bg-transparent dark:aria-disabled:bg-transparent dark:focus-visible:ring-brand-400 bg-transparent ring-1 ring-brand-500 ring-inset text-brand-400 hover:ring-brand-700 disabled:text-grey-600 disabled:ring-grey-600 disabled:hover:bg-transparent hover:bg-brand-100 focus-visible:ring-1 focus-visible:ring-brand-200 flex items-center&quot;]</value>
      <webElementGuid>30294606-3049-494b-973a-6098ebc0b63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[26]</value>
      <webElementGuid>4c827c61-a49c-4005-bb7c-e4a36bc7fe70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-v-0-2-18']/div/div[3]/div/button</value>
      <webElementGuid>51d52738-6d22-4ff2-a6da-5424cab10b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Pesan'])[1]/following::button[3]</value>
      <webElementGuid>514fb265-4226-4215-bc28-fb3e29960e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batalkan'])[1]/following::button[4]</value>
      <webElementGuid>6f542449-cd64-414f-acee-6baa0075f8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Pesan'])[2]/preceding::button[1]</value>
      <webElementGuid>cdfe8c81-7035-48a7-bc51-2816c5f5f074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div[3]/div/button</value>
      <webElementGuid>03bd8711-1ed7-49e0-a18b-6f2a3ddd38f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Batalkan' or . = 'Batalkan')]</value>
      <webElementGuid>bf94b553-9adf-4161-ad6e-f1f20064e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-v-0-2-19']/div/div[3]/div/button</value>
      <webElementGuid>4f393cbf-02dc-4166-8e2e-21e3e34a40f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
