<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_More Detail_bg-transparent hoverbg-g_3acdfd</name>
   <tag></tag>
   <elementGuidId>837fbae5-58cd-4ac9-be76-9296fc63478c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div[2]/div/div[5]/div/button[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5e18f0f-e5cd-401d-8ba3-e3f7e67f4cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-transparent hover:bg-grey-50 p-2 rounded-xs</value>
      <webElementGuid>4b779cf3-01fd-4208-9df0-e3eda30b0955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;mt-9 relative&quot;]/div[@class=&quot;fixed top-0 left-0 w-screen h-screen flex flex-col items-start&quot;]/div[@class=&quot;right-3 sm:right-6 bottom-28 sm:bottom-6 z-10 absolute transition-all ease-in-out duration-300&quot;]/div[@class=&quot;flex gap-2 bg-white/40 rounded-xs p-2 backdrop-blur-[6px]&quot;]/button[@class=&quot;bg-transparent hover:bg-grey-50 p-2 rounded-xs&quot;]</value>
      <webElementGuid>80cfd609-1efe-4912-bfd8-8592d209a924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div[2]/div/div[5]/div/button[4]</value>
      <webElementGuid>4ca8880c-0c0e-4bfb-8d66-12269facfee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Detail'])[1]/following::button[7]</value>
      <webElementGuid>5f2c7329-197e-406d-879a-e64a3839ada0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Popup'])[1]/following::button[9]</value>
      <webElementGuid>c0af2121-dd85-42d0-82fe-8081b35bc0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>ad54621a-0eec-4fe7-9409-3d67d473967a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
