<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Early Warning_maplibregl-canvas</name>
   <tag></tag>
   <elementGuidId>e010d96c-4216-4225-b689-9ce600a1668c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div[2]/div/div/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.maplibregl-canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>fb3b490f-7510-4cba-9d2d-ca4c187a0401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maplibregl-canvas</value>
      <webElementGuid>077190e4-faea-4d58-9ab5-85d7f5f0e2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d61e49d-c1c5-456c-aa18-9417e70b8768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Map</value>
      <webElementGuid>2dc2d871-c118-403a-828b-31e27c5a1a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>f5759ada-3a21-4cac-95e5-df0bcb880ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1366</value>
      <webElementGuid>f2cc1974-1bc8-45dd-ae28-ba2c0ae1511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>589</value>
      <webElementGuid>89bb91a8-2fd3-4bdf-ad98-81066881653d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;mt-9 relative&quot;]/div[@class=&quot;fixed top-0 left-0 w-screen h-screen flex flex-col items-start&quot;]/div[@class=&quot;map-wrap&quot;]/div[@class=&quot;map maplibregl-map&quot;]/div[@class=&quot;maplibregl-canvas-container maplibregl-interactive maplibregl-touch-drag-pan maplibregl-touch-zoom-rotate&quot;]/canvas[@class=&quot;maplibregl-canvas&quot;]</value>
      <webElementGuid>f489a4c4-eb13-40d9-a664-cbd694a3635a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div[2]/div/div/div/div/canvas</value>
      <webElementGuid>c70d2bd0-3bc2-4d74-bf80-3a7c96bffbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>4a9c1d0d-b5ce-4eea-b421-97d1821dd768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
