<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WASPADA_cursor-pointer p-2 bg-white rou_1e5e37</name>
   <tag></tag>
   <elementGuidId>4e827786-a921-4540-8f00-3f85c78a29b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headlessui-dialog-panel-v-0-2-34']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cursor-pointer.p-2.bg-white.rounded-xs.w-10.h-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf698ab7-86c1-48bc-8fc9-b6e9ab8c4dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer p-2 bg-white rounded-xs w-10 h-10</value>
      <webElementGuid>091e1f5d-d0e2-48a6-b865-d568e5c6150e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-panel-v-0-2-34&quot;)/div[@class=&quot;px-4 py-3 flex items-center gap-2&quot;]/div[@class=&quot;cursor-pointer p-2 bg-white rounded-xs w-10 h-10&quot;]</value>
      <webElementGuid>09d3dbf9-fc96-4c52-a9f0-b799adcfedc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-v-0-2-34']/div[3]/div</value>
      <webElementGuid>6d0f2390-5248-4d07-899d-4ee9a077c21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WASPADA'])[46]/following::div[2]</value>
      <webElementGuid>98ee4969-7be3-4305-b02c-18ff79b4b706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUMBAR - KOTA-PADANG BAGIAN SELATAN'])[2]/following::div[2]</value>
      <webElementGuid>1124a1a1-3506-4a48-a5d7-f0bc5b94e527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/preceding::div[5]</value>
      <webElementGuid>3ff39036-638e-43a3-b0e8-c1ccd9b8e360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>95190222-1bd3-46e4-862f-a7ae76b70f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
