<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Warning Tsunami PD-4Tsunami Warning PD-_fe1870</name>
   <tag></tag>
   <elementGuidId>91f070fe-3974-4e77-a03f-e758d7da36e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__nuxt']/div[2]/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>006b23a4-512a-45e7-8ec4-78cf56cac3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-white/45 p-1 w-full rounded-xs shadow-sm cursor-pointer flex gap-2</value>
      <webElementGuid>633aeb63-8e88-430e-b2a4-5b92c28ab21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Warning Tsunami PD-4Tsunami Warning PD-4, 10.060 LS, 112.660 BTMagnitude 8.9 Depth 18 km07/03/2025, 20.00.00 WIB</value>
      <webElementGuid>fb50f79e-8eb4-42d5-9d9c-11d2c0611d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;mt-9 relative&quot;]/div[@class=&quot;fixed top-0 left-0 w-screen h-screen flex flex-col items-start&quot;]/div[@class=&quot;flex-col z-10 absolute w-[20.75rem] bg-grey-100 rounded-sm left-6 overflow-hidden transition-all ease-in-out duration-300 hidden sm:flex h-[calc(100%-9.5rem)] top-[8rem]&quot;]/div[@class=&quot;flex flex-col gap-3 sm:h-full overflow-hidden&quot;]/div[@class=&quot;flex-1 overflow-y-scroll space-y-2 p-2&quot;]/div[@class=&quot;bg-white/45 p-1 w-full rounded-xs shadow-sm cursor-pointer flex gap-2&quot;]</value>
      <webElementGuid>c425435f-42ac-4f0c-8158-47894a5f0111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>96adaff1-67d6-423d-b524-6e497a7c0b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Detail'])[1]/following::div[5]</value>
      <webElementGuid>20ea0d34-1ed2-492d-ad29-db5da73884aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Popup'])[1]/following::div[7]</value>
      <webElementGuid>4fc3496a-3c75-47b0-b74c-5e813e4060bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>d1bfc409-c8f8-40ec-a457-e2a6fdaa22d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Warning Tsunami PD-4Tsunami Warning PD-4, 10.060 LS, 112.660 BTMagnitude 8.9 Depth 18 km07/03/2025, 20.00.00 WIB' or . = 'Warning Tsunami PD-4Tsunami Warning PD-4, 10.060 LS, 112.660 BTMagnitude 8.9 Depth 18 km07/03/2025, 20.00.00 WIB')]</value>
      <webElementGuid>2156c339-e0bb-4c33-81b1-9a2578a1328a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
