<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multi Hazard Early Warning System_email</name>
   <tag></tag>
   <elementGuidId>57346d42-dda0-4d19-99c2-41b13f54e7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#v-0-1-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='v-0-1-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22ab1379-5d25-4e41-9388-296c1a24c1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>v-0-1-1</value>
      <webElementGuid>3920517f-a838-4389-bfac-b6d43ad5ec10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>96afa5b2-fc1a-48ec-9451-2c76ee96b7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6febd6e9-249f-47bc-a3ac-3c65a2f60adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>7f5d22a2-f269-41fc-80eb-6652ffe865e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative block w-full disabled:cursor-not-allowed disabled:opacity-75 focus:outline-none border-0 form-input rounded-xs placeholder-gray-400 dark:placeholder-gray-500 text-base px-3.5 py-2.5 shadow-sm bg-grey-200 dark:bg-grey-700 text-grey-black dark:text-white ring-1 ring-inset ring-grey-600 dark:ring-grey-700 focus:ring-2 focus:ring-primary-500 dark:focus:ring-primary-400 placeholder:text-grey-500</value>
      <webElementGuid>9e747b6e-c957-4093-a49e-284cd6641ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase import static com.kms.katalon.core.testdata.TestDataFactory.findTestData import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile import com.kms.katalon.core.model.FailureHandling as FailureHandling import com.kms.katalon.core.testcase.TestCase as TestCase import com.kms.katalon.core.testdata.TestData as TestData import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW import com.kms.katalon.core.testobject.TestObject as TestObject import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows import internal.GlobalVariable as GlobalVariable import org.openqa.selenium.Keys as Keys  WebUI.openBrowser('')  WebUI.navigateToUrl(GlobalVariable.url)  WebUI.maximizeWindow()  WebUI.mouseOver(findTestObject('landing0/button_Latest Alerts'))  //WebUI.scrollToElement(findTestObject('landing0/button_Latest Alerts'), 10000) WebUI.click(findTestObject('Object Repository/landing0/button_Latest Alerts'))  WebUI.setText(findTestObject('Object Repository/landing0/input_Multi Hazard Early Warning System Map_email'), GlobalVariable.username)  WebUI.setEncryptedText(findTestObject('Object Repository/landing0/input_Multi Hazard Early Warning System Map_2d5bf2'),      '76urUe1T5hacINtx1jFsbA==')  WebUI.click(findTestObject('Object Repository/landing0/button_Sign In'))  WebUI.click(findTestObject('Object Repository/login/button_Back'))</value>
      <webElementGuid>25ee6275-782d-404e-98ff-873a71234019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v-0-1-1&quot;)</value>
      <webElementGuid>394b850c-6ec6-47e2-8d99-ff74dfc1c494</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='v-0-1-1']</value>
      <webElementGuid>e28b4681-e91a-4c4b-a1cf-e12000dd7bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div/form/div/div[2]/div/input</value>
      <webElementGuid>98b330cb-60c1-4d66-97d1-595d78460480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8531d781-e04a-4310-9ca1-be3db3b298e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'v-0-1-1' and @name = 'email' and @type = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>768ccb6c-b633-47d3-a3a0-c3b877489ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
